### ISSUE TITLE
Main and transaction list screen

### ISSUE THREAD

**Issue by anoochit** [anoochit/mobile_web3_boilerplate#3]
The boilerplate doesn't have the main screen to display a coins list in the wallet and recent transactions. I need a main screen to show a coin list, and recent transaction which has a status.

**Comment by samitkapoor** [comment]
Hey @anoochit, I would like to work on this issue.

Do you have any designs you would like me to implement in the application? 
If yes, can you please share that with me?
If not, can you please share more information regarding how you want things to be displayed on the main screen?

**Comment by anoochit** [comment]
> Hey @anoochit, I would like to work on this issue.
> 
> Do you have any designs you would like me to implement in the application? If yes, can you please share that with me? If not, can you please share more information regarding how you want things to be displayed on the main screen?

Hi, I am not a good UI designer so I have only a draft design. My idea is the main screen should have 

* a dropdown menu to select blockchain network
* a balance of coin base for the network eg: ETH for Ethereum
* a tab bar for selecting between assets  and activity (aka recent transactions)
 * assets tap show a list of the token (maybe ERC20 or NFT) with the balance of each token
 * activity tab shows a list of recent activity eg: send, received, and show status success, failed or cancel.

I have a draft UI in [jamboard](https://jamboard.google.com/d/19RI4YnFIJd80BANzLRKkjwfJNhhvI_kDeKLleGVDBdQ/edit?usp=sharing). 

Thank you.

**Comment by samitkapoor** [comment]
Thanks @anoochit 
Can you please assign this issue to me, I'd like to work on it
